language: generic

sudo: required

services: docker

###############################################################################
# Load up a docker container which has texlive 2015 installed, then
# update it under instructions from Dockerfile
install:
  - docker build -t harshjv/texlive-2015 .
  - docker ps -a

###############################################################################
before_script:
  # Check texlive version
  - tlmgr version -v
  # Check which tex packages we have available
  - tlmgr info --only-installed ||
        echo "Couldn't retrieve the texlive package list!"

###############################################################################
script:
  - latex -halt-on-error -interaction nonstopmode small2e
  - pdflatex -halt-on-error -interaction nonstopmode small2e
